### ISSUE TITLE
Keyboard shortcuts for Custom Timers and/or ability to pin custom timers in Raycast menu

### ISSUE THREAD

**Issue by markodevinci** [ThatNerdSquared/timers-for-raycast#11]
I think it would a great addition/ux improvement if the ability to start a custom timer from a user-defined keyboard shortcut was a feature. Alternatively (or in addition to), the ability for the Custom Presets made under "Manage Timers" to be pinnable to the main menu of Raycast, like how the default timers are able to be. This would be a nice QOL improvement, as it would save a step of having to enter the "Manage Timers" menu and then selecting the custom timer you'd like to begin (just being able to launch Raycast and search for it directly/have it pinned).

Side note: A keyboard shortcut that expands the menu bar list could be something worth looking into.

Also, thanks for the awesome extension, keep up the good work!

**Comment by ThatNerdSquared** [comment]
Hi @markodevinci - thanks for using Timers!

Great suggestion - there's not a way for us to dynamically populate the main Raycast menu with commands, unfortunately. However, I have heard from other extension authors that it's possible to work around this using deeplinks/quicklinks, which would let you access custom timers using keybinds, from root search, etc. I'm currently working on this - assuming everything works out fine, it'll probably be out sometime late December.

As for keyboard shortcut expanding menu bar list, I'm not actually sure if that's possible, but I will definitely look into it!

**Comment by ThatNerdSquared** [comment]
I've added a way to add a custom timer preset to your root search as a quicklink in the latest update. That will let you pin them to favourites, search them from root search, assign keyboard shortcuts, etc. You can set this up from the 

Keyboard shortcut to expand menu bar list is, as far as I can tell, not technically possible - that's not something Raycast controls, I think macOS just doesn't provide a mechanism for it.

Closing this issue now, feel free to reopen if the shipped feature
