### ISSUE TITLE
Menu bar not showing

### ISSUE THREAD

**Issue by tansanDOTeth** [ThatNerdSquared/timers-for-raycast#14]
Hi, thanks for this cool app! I tried selecting "Timers Menu Bar" and I don't see anything showing up in my Menu bar. Is there something else I need to configure?

**Comment by ThatNerdSquared** [comment]
Hi @tansanDOTeth, thanks for the report

**Comment by ThatNerdSquared** [comment]
Hi @tansanDOTeth, thanks for the report. Just double-checking a few things:

- you've checked that the menubar icon isn't being hidden by any menu-bar-icon-hiding apps like Bartender, Hidden Bar, etc?
- the menubar icon doesn't show when a stopwatch/timer is running?
- you don't have the "Show Menu Bar Item When" preference set to "Never"?

**Comment by tansanDOTeth** [comment]
> Hi @tansanDOTeth, thanks for the report. Just double-checking a few things:
> 
> * you've checked that the menubar icon isn't being hidden by any menu-bar-icon-hiding apps like Bartender, Hidden Bar, etc?
I am pretty sure I am just running vanilla; I don't know what those things are. How can I check?

> * the menubar icon doesn't show when a stopwatch/timer is running?
I don't see anything showing up when I run a timer

> * you don't have the "Show Menu Bar Item When" preference set to "Never"?
How do I check?

**Comment by ThatNerdSquared** [comment]
> I am pretty sure I am just running vanilla; I don't know what those things are. How can I check?

That's okay, those are third-party apps a lot of people use to hide icons in the menu bar, and sometimes they get in the way of things. If you haven't installed them yourself it's likely not the issue.


> > you don't have the "Show Menu Bar Item When" preference set to "Never"?

> How do I check?

Raycast Preferences > Extensions > Timers, and the preferences should show in the right sidebar:

![Screenshot 2024-01-20 at 14 34 32](https://github.com/ThatNerdSquared/timers-for-raycast/assets/72814106/b215db94-5364-4cc9-a742-895f90d9fcdf)

**Comment by tansanDOTeth** [comment]
> Raycast Preferences > Extensions > Timers, and the preferences should show in the right sidebar:

This was it! thank you for your help!

**Comment by ThatNerdSquared** [comment]
No problem :) Can I ask you when you installed Timers? (This setting once had a very non-intuitive default, which I changed in a later update, but I'm not sure if my change to it worked or not.)

**Comment by tansanDOTeth** [comment]
> No problem :) Can I ask you when you installed Timers? (This setting once had a very non-intuitive default, which I changed in a later update, but I'm not sure if my change to it worked or not.)

Just yesterday, but I don't recall if there was a setting for that

**Comment by ThatNerdSquared** [comment]
Hmm, okay. Thanks for the info. Closing this issue now, feel free to reopen or file another one if you need any more help :)
