### ISSUE TITLE
no sound is playing when the timer is finished

### ISSUE THREAD

**Issue by ivanmauricio** [ThatNerdSquared/timers-for-raycast#15]
### Description

no sound is playing when the timer is finished.

i can play a sound if i use the `preview alert sounds` command

i also ran this command in the terminal and it works: `afplay /System/Library/Sounds/Hero.aiff`

and here are the relevant settings

![CleanShot 2024-03-26 at 12 26 26](https://github.com/raycast/extensions/assets/12462448/33eedaf0-e8ef-48f8-9b90-231ab95ab66d)

(i've also tried with different selected sounds)

### Steps To Reproduce

1. set a timer off
2. wait for it to end
3. no sound plays

**Comment by ThatNerdSquared** [comment]
Closing this as I see [the issue has been filed on the main raycast repo](https://github.com/raycast/extensions/issues/11500) - follow there for updates.
