### ISSUE TITLE
Can't see default timers

### ISSUE THREAD

**Issue by himat** [ThatNerdSquared/timers-for-raycast#18]
Hey I just installed the extension but I don't see any of the default timers

<img width="775" alt="image" src="https://github.com/ThatNerdSquared/timers-for-raycast/assets/1156974/2e7612f2-b996-493f-a53b-28bb53686ffd">

Here's my Manage Timers view (I created two custom ones)
<img width="754" alt="image" src="https://github.com/ThatNerdSquared/timers-for-raycast/assets/1156974/19d4a407-5ad9-404f-b540-9cb3ab65eada">

**Comment by ThatNerdSquared** [comment]
Hi @himat, thanks for using Timers! Many of the presets are disabled by default to avoid cluttering Raycast's root search. If you go into the extension settings, you should be able to enable the ones you want.

**Comment by himat** [comment]
Oh! I see now, yep got it.

Separately, is there also a way to make a custom timer of mine show up in the global raycast command list? Since right now I have to go into "Manage Timers" and then scroll and click on the one I want instead of being able to type to search for it globally after opening raycast

**Comment by ThatNerdSquared** [comment]
Pressing ⌘K on a custom preset in "Manage Timers" should show an "Add Preset to Root Search" action, which allows you to easily make the preset show up in your root search.

It's a little weird (technically works by hooking up a Quicklink to a deeplink for the preset), but that's the only way it works in Raycast at the moment :)

**Comment by himat** [comment]
Amazing, thanks!
