### ISSUE TITLE
Set Custom Timer from the Menu bar

### ISSUE THREAD

**Issue by albas99** [ThatNerdSquared/timers-for-raycast#2]
The menu bar presets are okay but I don't use them very often and I prefer setting my own custom timer, it'll be nice if I'll be able to set my own custom timer directly from the menu bar and also if possible the ability to remove all other presets from the menu bar as well.

**Comment by ThatNerdSquared** [comment]
Hi @albas99, thanks for using Timers! Would you prefer to remove custom presets from the menu bar as well? Or just the default ones?

**Comment by albas99** [comment]
I think it'll be great if the user gets full control over what to place in the menu bar, that might include also choosing the add or remove any type of preset whether the default or custom.

**Comment by ThatNerdSquared** [comment]
Sounds good - I'll tinker with it later this week 👍

**Comment by ThatNerdSquared** [comment]
Hey @albas99, a quick update - the ability to set a custom timer from the menu bar should be available to you now. Full customizability of the presets in the menu bar is still in the works.

**Comment by albas99** [comment]
> Hey @albas99, a quick update - the ability to set a custom timer from the menu bar should be available to you now. Full customizability of the presets in the menu bar is still in the works.

Hey, sorry for taking too long to reply. I've checked it out and it's working great. Thanks for the update.

**Comment by ThatNerdSquared** [comment]
(Finally) closing this now - the newly released "Configure Presets in Menu Bar" command should meet your needs 👍
