### ISSUE TITLE
The timer not starting with this new ring notification. 

### ISSUE THREAD

**Issue by abhii-roy** [ThatNerdSquared/timers-for-raycast#20]
I am getting this notification, but the timer is not starting after this notification. 

<img width="354" alt="image" src="https://github.com/user-attachments/assets/6b6a211c-195f-423a-b2ab-dea91aecb95b">

**Comment by ThatNerdSquared** [comment]
Hi @roy-abhi-roy, thanks for using Timers!

I'm currently investigating this. In this situation, how are you starting the timer? Does it work properly when you start a timer from the "Manage Timers" command?

So far I've isolated it to launching presets from root search - a workaround for now is to start a timer from "Manage Timers" which seems to behave properly once you press enter the alert.

**Comment by ThatNerdSquared** [comment]
This should be resolved in the latest version of the extension - use the "Check For Extension Updates" command to grab the latest version of your extensions, and your timers should start properly :)

Would you mind letting me know if this works for you?

**Comment by roy-abhi-roy** [comment]
Yes I confirm, it is working.

**Comment by ThatNerdSquared** [comment]
Great! Thanks for the bug report - glad we were able to get this fixed :)
