### ISSUE TITLE
Preview sound in settings

### ISSUE THREAD

**Issue by akd-io** [ThatNerdSquared/timers-for-raycast#3]
Hey, love this extension!

I wanted to change the sound today and ended up going here on GitHub to download the assets and listen to them.

Maybe it'd be a better experience for the user to be able to preview the sounds in the extension settings.

Again, thank you for the extension, and have a great day!

**Comment by ThatNerdSquared** [comment]
Hey there, thanks for using Timers!

That sounds like a great idea - I'm not sure if I can do it directly in extension settings, but I may create a command that allows you to preview each sound effect in a list-like view.

Thanks for the suggestion!

**Comment by ThatNerdSquared** [comment]
Hey @akd-io, a quick update - I've implemented a command that does this:
![Screenshot 2022-12-21 at 18 46 24](https://user-images.githubusercontent.com/72814106/209044356-9a8daf0c-0034-49cc-9ec0-9771c2220f32.png)

I've made a PR, so this feature should be out shortly: https://github.com/raycast/extensions/pull/3999

**Comment by akd-io** [comment]
Oh that's super cool, thanks a lot @ThatNerdSquared!
