### ISSUE TITLE
Allow Pausing stopwatches

### ISSUE THREAD

**Issue by mcascone** [ThatNerdSquared/timers-for-raycast#4]
When i stop a stopwatch, i don't necessarily want it to just disappear.

Implement an option to leave the stopwatch in the list of available stopwatches.

Paused stopwatches can be restarted, canceled, or stopped.

**Comment by ThatNerdSquared** [comment]
Hey @mcascone, thanks for using Timers!

Great suggestion - would you want this setting to be available per-stopwatch (perhaps as another keybind on the list item) or a global setting for all stopwatches (something like a preference in Raycast settings)?

**Comment by mcascone** [comment]
I think it should always stay, because having the stopwatch disappear upon stopping really reduces the usefulness.

**Comment by ThatNerdSquared** [comment]
Hey @mcascone - this feature is finally live in Raycast! Thanks for the feedback \:)
