### ISSUE TITLE
Edit volume of timer notification

### ISSUE THREAD

**Issue by gwenwindflower** [ThatNerdSquared/timers-for-raycast#5]
Hi! First of all, I love this extension, amazing work. Had a suggestion on something that makes me use the extension way less than I would otherwise though: I find the notification to be brutally loud 😅. Could you add a volume setting so it's not blasting me at max volume? It scares the 💩 out of me when I'm in a flow state doing poms 🍅.

Thanks for listening, and again, great work!

**Comment by ThatNerdSquared** [comment]
Hi @gwenwindflower, thanks for using Timers!

Sounds good - I've never thought about this but it makes sense, and it looks like `afplay` (which I use to play the alert sound under the hood) has a [volume flag](https://ss64.com/osx/afplay.html) I can mess around with. Thanks for the suggestion!

**Comment by birnstiel** [comment]
kind of related, so I'll add it here instead of a new issue: my computer is usually muted, so I don't hear anything if the timer is over. Perhaps some notification window could be added as option. I used this in a [python timer for Alfred](https://github.com/birnstiel/ttimer/blob/6c80198e0ab06ceb7e57c0b02335cfbdb1ddd96e/ttimer.py#L89).

**Comment by ThatNerdSquared** [comment]
@birnstiel you should get a notification like this:

<img width="359" alt="Screenshot 2023-03-03 at 09 16 04" src="https://user-images.githubusercontent.com/72814106/222785048-49bc32df-6f53-463a-ae5d-26d76334a444.png">

If you use Focus modes, you may need to allow Script Editor notifications to ensure it doesn't get blocked out.

I've also just found a bug with the "Ring Continuously" mode where the ringing blocks the notification send - I'll push a fix for that now.

**Comment by birnstiel** [comment]
Ah yes it was the work focus - now it works - thanks a lot!

**Comment by ThatNerdSquared** [comment]
The fix is officially live in Raycast - thanks for the feedback \:) Hope you enjoy using Timers!
