### ISSUE TITLE
Remove timer length and title from top menu-bar. 

### ISSUE THREAD

**Issue by daninoks** [ThatNerdSquared/timers-for-raycast#7]
Hello
Is it possible to remove timer length and icon when timer is running, and left only countdown in datetime fromat? 
Currently size of top menu widget is too large, I suppose...
<img width="208" alt="image" src="https://user-images.githubusercontent.com/51907465/236144719-dbb26110-e162-44e5-9a90-3e62c14d3e8e.png">

UPD: And also visual end-timer pop-up banner is must have for it, I just realized, if sounds are off, timer just ends  

Thanks for your work <3

**Comment by ThatNerdSquared** [comment]
Hi @daninoks, thanks for using Timers!

It's not yet possible to remove the title and icon, but I am working on it. Thanks for the suggestion.

> And also visual end-timer pop-up banner is must have for it, I just realized, if sounds are off, timer just ends

There should be a banner similar to the below:
![Screenshot 2023-05-04 at 18 09 57](https://user-images.githubusercontent.com/72814106/236359777-b316a195-db11-410b-88d9-2c92602dfc10.png)

Have you followed the instructions from the README?
> *Note: if you do not receive notifications from the timer completion, you may need to allow Script Editor notifications in your Focus settings.*

**Comment by ThatNerdSquared** [comment]
Hi @daninoks, quick update - the ability to remove the icon has been shipped and should be available to you now! I've implemented the ability to remove the title in the above commit, that will be shipped shortly.
