### ISSUE TITLE
Menu bar items are missing since the latest update

### ISSUE THREAD

**Issue by jan-osch** [ThatNerdSquared/timers-for-raycast#9]
Hello! First of all a big "Thank you" for creating this handy extension. I'm using it to remind myself to get up every 30 minutes (hello sciatica).

With the most recent update, the extension stopped working properly. It doesn't show a Menu Bar item anymore, and after a timer elapses the sound continues indefinitely.

Raycast version 1.61.1

**Comment by ThatNerdSquared** [comment]
Hi @jan-osch, thanks for the bug report. How long has this been happening? This will help me pinpoint where things went wrong - I pushed a new update about 14 hours ago so not sure if that's what caused it.

A couple things to check:
- The sound continuing indefinitely sounds like the "Ring Continuously" feature has been enabled in the extension settings - I did make that the default recently. Does going into the extension settings and disabling that solve your problem? Alternatively, the sound should stop after you stop a timer or run the "Dismiss Ringing Timer" command.
- For the menu bar item not showing, have you tried running the "Timers Menu Bar" command, and does that fix it? Is the "Show Menu Bar Item When" preference in the extension settings set to "Always"?

**Comment by jan-osch** [comment]
The issue started yesterday morning ~ I noticed it around 09:00 am UTC on Tuesday, November 7th, 2023.

The continuous sound: I used to have that option enabled, but the sound would only stop when I dismissed the timer. Now dismissing the timer does not stop the sound - I have to use `ps aux | grep timer | aw 2 | xargs kill -9`

Menu bar: running the command helped to show the icon, however, the preview of time remaining is not showing instantly, I have to click it again 




https://github.com/ThatNerdSquared/timers-for-raycast/assets/11651780/bde39a42-f8c3-470f-9928-e8b9497b6809

**Comment by jan-osch** [comment]
❤️ the issue is resolved! 🙇‍♂️ thank you for fixing it
